In [1]:
import pandas as pd


In [2]:
df=pd.read_csv("score.csv")

In [3]:
df.head()

,Age,Gender,Annual_Income,Spending_Score,Purchased
0,23,Male,32000,45,0
1,45,Female,64000,78,1
2,34,Male,58000,60,1
3,25,Female,35000,40,0
4,52,Male,72000,65,1


In [4]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])

In [5]:
df

,Age,Gender,Annual_Income,Spending_Score,Purchased
0,23,1,32000,45,0
1,45,0,64000,78,1
2,34,1,58000,60,1
3,25,0,35000,40,0
4,52,1,72000,65,1
5,46,0,69000,70,1
6,29,1,42000,55,0
7,31,0,48000,58,0
8,27,1,39000,52,0
9,41,0,61000,66,1


In [32]:
from sklearn.preprocessing import StandardScaler
scale=StandardScaler()
forscalinng=['Age','Gender','Annual_Income','Spending_Score']
scaled=scale.fit_transform(df[forscalinng])
scaled

array([[-1.44433273,  1.        , -1.57452517, -1.40566175],
       [ 1.3676425 , -1.        ,  1.08664413,  2.0389054 ],
       [-0.03834512,  1.        ,  0.58767489,  0.16005059],
       [-1.18869862, -1.        , -1.32504055, -1.92756586],
       [ 2.26236189,  1.        ,  1.75193646,  0.68195471],
       [ 1.49545956, -1.        ,  1.50245184,  1.20385882],
       [-0.6774304 ,  1.        , -0.74290977, -0.36185352],
       [-0.42179628, -1.        , -0.24394052, -0.04871105],
       [-0.93306451,  1.        , -0.99239439, -0.67499599],
       [ 0.85637428, -1.        ,  0.83715951,  0.78633553],
       [ 0.217289  ,  1.        ,  0.25502873,  0.05566977],
       [-0.80524745, -1.        , -0.65974822, -0.46623434],
       [-0.16616217,  1.        , -0.07761744,  0.26443142],
       [ 0.60074016, -1.        ,  0.92032105,  0.47319306],
       [-1.57214979,  1.        , -1.74084826, -1.71880421],
       [ 1.23982544, -1.        ,  1.33612876,  1.30823965],
       [ 0.34510605,  1.

In [33]:
df.columns

Index(['Age', 'Gender', 'Annual_Income', 'Spending_Score', 'Purchased'], dtype='str')

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             30 non-null     int64
 1   Gender          30 non-null     int64
 2   Annual_Income   30 non-null     int64
 3   Spending_Score  30 non-null     int64
 4   Purchased       30 non-null     int64
dtypes: int64(5)
memory usage: 1.3 KB


In [35]:
df

,Age,Gender,Annual_Income,Spending_Score,Purchased
0,23,1,32000,45,0
1,45,0,64000,78,1
2,34,1,58000,60,1
3,25,0,35000,40,0
4,52,1,72000,65,1
5,46,0,69000,70,1
6,29,1,42000,55,0
7,31,0,48000,58,0
8,27,1,39000,52,0
9,41,0,61000,66,1


In [36]:
X = df.drop('Purchased', axis=1)
y = df['Purchased']

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train, X_test, y_train, y_test

(    Age  Gender  Annual_Income  Spending_Score
 28   34       0          53000              59
 24   38       1          55000              60
 12   33       1          50000              61
 0    23       1          32000              45
 4    52       1          72000              65
 16   37       1          56000              64
 5    46       0          69000              70
 13   39       0          62000              63
 11   28       0          43000              54
 22   40       1          60000              67
 1    45       0          64000              78
 2    34       1          58000              60
 25   29       0          41000              50
 3    25       0          35000              40
 21   24       0          34000              44
 26   43       1          65000              72
 18   30       1          47000              56
 29   31       1          46000              55
 20   35       1          52000              62
 7    31       0          48000         

C:\Users\khair bakhsh\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [ ]:
y_pred = model.predict(X_test)

In [48]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

new_customer = [[40,1, 70000, 15]]  # assuming Gender encoded (Male=1)

new_customer = scale.transform(new_customer)

prediction = model.predict(new_customer)

print(prediction)
prediction

[1]


C:\Users\khair bakhsh\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\khair bakhsh\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\khair bakhsh\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRe

array([1])

In [51]:
from  sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(X_train,y_train)
pred=model.predict(X_test)
customer = [[40,1, 80000, 15]]  # assuming Gender encoded (Male=1)

new_customer = scale.transform(customer)

prediction = model.predict(new_customer)

print(prediction)
prediction

[0]


C:\Users\khair bakhsh\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\khair bakhsh\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

# 1. Define X and y (unscaled for now)
X = df.drop('Purchased', axis=1)
y = df['Purchased']

# 2. Split the data FIRST
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Scale the data AFTER splitting
scale = StandardScaler()
X_train_scaled = scale.fit_transform(X_train) # Fit and transform on training data
X_test_scaled = scale.transform(X_test)       # Only transform on test data

# 4. Train the model on the SCALED data
model = LogisticRegression()
model.fit(X_train_scaled, y_train) # That convergence warning should disappear now!

# 5. Predict for your new customer
new_customer = [[40, 1, 70000, 15]] 
new_customer_scaled = scale.transform(new_customer) # Scale using the same scaler
prediction = model.predict(new_customer_scaled)

print(prediction)

[0]


C:\Users\khair bakhsh\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
